//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public long Code { get; set; }
        public long RXCUI_DrugCoded_ { get; set; }
        public Nullable<long> GENERIC_RXCUI { get; set; }
        public string TTY_DrugDBCodeQualifier_ { get; set; }
        public string FULL_NAME { get; set; }
        public string RXN_DOSE_FORM { get; set; }
        public string FULL_GENERIC_NAME { get; set; }
        public string BRAND_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string ROUTE { get; set; }
        public string NEW_DOSE_FORM { get; set; }
        public string STRENGTH { get; set; }
        public string SUPPRESS_FOR { get; set; }
        public string DISPLAY_NAME_SYNONYM { get; set; }
        public Nullable<bool> IS_RETIRED { get; set; }
        public Nullable<long> SXDG_RXCUI { get; set; }
        public string SXDG_TTY { get; set; }
        public string SXDG_NAME { get; set; }
        public string PSN_DrugDescription_ { get; set; }
        public string NCPDP_Quantity_Term { get; set; }
        public string Potency_Unit_Code { get; set; }
        public Nullable<long> DEA_Schedule__ { get; set; }
        public string DEA_Schedule { get; set; }
        public string Ingredients { get; set; }
        public string Drug_Interaction { get; set; }
        public string Unit_Source_Code { get; set; }
        public string Code_List_Qualifier { get; set; }
    }
}
