//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        public long id { get; set; }
        public string APP { get; set; }
        public string NCPDP { get; set; }
        public string NCPDP_safe { get; set; }
        public string Mutually_Defined_ID { get; set; }
        public string Mutually_Defined_ID_safe { get; set; }
        public string NPI { get; set; }
        public string NPI_safe { get; set; }
        public string Business_Name { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ZipCode_safe { get; set; }
        public string Country_Code { get; set; }
        public Nullable<bool> Country_Code__1 { get; set; }
        public Nullable<long> Latitude { get; set; }
        public Nullable<long> Longitude { get; set; }
        public string Pharmacy_Phone { get; set; }
        public string Pharmacy_Phone_safe { get; set; }
        public string Pharmacy_Fax { get; set; }
        public string Pharmacy_Fax_safe { get; set; }
        public string Types { get; set; }
        public string Script_Msg_Accepted { get; set; }
        public string Specialized_Msg_Accepted { get; set; }
        public string Connectivity_Status { get; set; }
        public Nullable<bool> Accept_TSO { get; set; }
        public Nullable<System.DateTime> DEA_Audit_Exp { get; set; }
        public Nullable<bool> Test_Pharmacy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    }
}
