//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public long Id { get; set; }
        public Nullable<long> AppId { get; set; }
        public string Drug_Display_Name { get; set; }
        public Nullable<long> RXCUI_DrugCode_ { get; set; }
        public string Drug_Full_Name { get; set; }
        public string Quantity { get; set; }
        public string DrugFrequency { get; set; }
        public string Schedule { get; set; }
        public string FoodStatus { get; set; }
        public string Days { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string RecordStatud { get; set; }
    }
}
